### ISSUE TITLE
Initial Public Release Checklist

### ISSUE THREAD

**Issue by evansb** [mobius-js/mobius-core#2]
## Layout Engine
- [ ] Layout algorithms: split vertical, split horizontal, stacked
- [ ] Custom layout algorithm

## Components
- [ ] Text editor
- [ ] Debugger
- [ ] Markdown view

## Document Engine
- [ ] Sync with local storage
